import type { Metadata } from 'next'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import Header from '@/components/Header'
import {
	useQuery,
	useMutation,
	useQueryClient,
	QueryClient,
	QueryClientProvider,
} from '@tanstack/react-query'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="mt-6 max-w-[1280px] mx-auto">
				<QueryClientProvider client={queryClient}>
					<Header />
					{children}
					<Toaster />
				</QueryClientProvider>
			</body>
		</html>
	)
}
