version: '3.8'
services:
  backend:
    image: kutaui/shortie-backend:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - shortie-network

  frontend:
    image: kutaui/shortie-frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://shortie-api.kutaybekleric.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shortie-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: always
    networks:
      - shortie-network

networks:
  shortie-network:
    driver: bridge
