// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        int64
	UrlID     int64
	CreatedAt pgtype.Timestamp
}

type Url struct {
	ID        int64
	LongUrl   string
	Code      string
	CreatedAt pgtype.Timestamp
	UserID    int64
}

type User struct {
	ID        int64
	Email     string
	Name      string
	Password  string
	CreatedAt pgtype.Timestamp
}
